pool:
  vmImage: 'ubuntu-latest'

trigger:
- main

pr: none

stages:
  - stage: MavenBuild
    displayName: 'Build Release candidate with Maven'
    jobs:
      - job: MavenPackage
        displayName: 'Package JAR with Maven'
        steps:
          - task: Maven@3
            displayName: 'Compile code'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: false
              goals: 'compile'
          - task: Maven@3
            displayName: 'Package JAR'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: false
              goals: 'package'
          - task: GitHubRelease@1
            inputs:
              gitHubConnection: 'GitHub'
              repositoryName: 'qbituniverse/qbitcraft'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'manual'
              tag: 'v1.0.0'
              assets: '$(Build.SourcesDirectory)/target/dist/*.jar'
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'commitBased'