pool:
  vmImage: 'ubuntu-latest'

trigger:
- develop

pr: none

stages:
  - stage: MavenBuild
    displayName: 'Build with Maven'
    jobs:
      - job: MavenPackage
        displayName: 'Package JAR with Maven'
        steps:
          - task: replacetokens@3
            displayName: Replace build version
            inputs:
              targetFiles: 'pom.xml'
          - task: Maven@3
            displayName: 'Deploy JAR'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              jdkArchitectureOption: 'x64'
              mavenAuthenticateFeed: true
              publishJUnitResults: false
              goals: 'deploy'