pool:
  vmImage: 'ubuntu-latest'

pr:
  branches:
    include:
    - '*'

stages:
  - stage: MavenBuild
    displayName: 'Check code compile for PR with Maven'
    jobs:
      - job: MavenCompile
        displayName: 'Compile with Maven'
        steps:
          - task: Maven@3
            displayName: 'Compile code'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: false
              goals: 'compile'